b{iit}.u_i = double(u_i);
b{iit}.qA_i = double(qA_i);
b{iit}.qB_i = double(qB_i);
b{iit}.qC_i = double(qC_i);
b{iit}.qD_i = double(qD_i);
b{iit}.qOmega_i = double(qOmega_i);
b{iit}.T_i = double(T_i);
b{iit}.t_p_i = double(t_p_i);
b{iit}.C_i = double(C_i);
b{iit}.X_i = double(X_i);
b{iit}.Y_i = double(Y_i);
b{iit}.Z_i = double(Z_i);
b{iit}.t_f_i = double(t_f_i);
b{iit}.S_i = double(S_i);
b{iit}.v_i = double(v_i);
b{iit}.KE_s_i = double(KE_s_i);
b{iit}.KE_f_i = double(KE_f_i);
display("big.m");